services:
  - type: web
    name: video-summarizer
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"
    buildpacks:
      - url: https://github.com/render-examples/python-3.9-buildpack.git
      - url: https://github.com/renderinc/render-buildpack-ffmpeg.git