services:
  - type: web
    name: video-summarizer
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"